[package]
name = "microvm-builder-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
snafu = "0.8"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

clap = { version = "4", features = ["derive"] }

nix = { version = "0.30", features = ["process", "signal"] }
tokio = { version = "1", features = [
  "fs",
  "io-std",
  "io-util",
  "macros",
  "net",
  "process",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
